ARG version=9
FROM almalinux:${version}
ARG course="DevOps with AWS" \
    duration="120hrs"
ENV duration=$duration
RUN echo "Course: $course, duration: $duration, version: $version"
CMD ["sleep","100"]